version: "3.8"

services:
  chartbrew:
    image: chartbrew/chartbrew:latest
    restart: unless-stopped
    ports:
      - 4018:4018 # Frontend
      - 4019:4019 # API
    environment:
      - PORT=4018
      - CB_DB_USER=${CB_DB_USERNAME}
      - CB_DB_PASSWORD=${CB_DB_PASSWORD}
      - CB_DB_HOST=db
      - CB_DB_NAME=${CB_DB_NAME}
      - CB_DB_PORT=3306
      - CB_ENCRYPTION_KEY=${CB_ENCRYPTION_KEY}
      - CB_REDIS_HOST=redis
      - CB_REDIS_PASSWORD=${CB_REDIS_PASSWORD}
    depends_on:
      - db
      - redis

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${CB_DB_NAME}
      MYSQL_USER: ${CB_DB_USERNAME}
      MYSQL_PASSWORD: ${CB_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DEFAULT_AUTH: caching_sha2_password
    volumes:
      - mysqldata:/var/lib/mysql

  redis:
    image: redis:latest
    restart: unless-stopped
    command: redis-server
    volumes:
      - redisdata:/data

volumes:
  mysqldata:
  redisdata:
