services:
  db:
    image: mysql:8.4
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${CB_DB_NAME}
      MYSQL_USER: ${CB_DB_USERNAME}
      MYSQL_PASSWORD: ${CB_DB_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: true
      MYSQL_DEFAULT_AUTH: caching_sha2_password
    volumes:
      - chartbrew-db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: unless-stopped
    environment:
      CB_REDIS_HOST: redis
      REDIS_PASSWORD: ${CB_REDIS_PASSWORD}
    ports:
      - 6379:6379

  chartbrew:
    build:
      context: .
      dockerfile: Dockerfile.override
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=4018
      - CB_DB_HOST=${CB_DB_HOST}
      - CB_DB_NAME=${CB_DB_NAME}
      - CB_DB_USERNAME=${CB_DB_USERNAME}
      - CB_DB_PASSWORD=${CB_DB_PASSWORD}
      - CB_DB_PORT=${CB_DB_PORT}
      - CB_ENCRYPTION_KEY=${CB_ENCRYPTION_KEY}
      - CB_REDIS_PASSWORD=${CB_REDIS_PASSWORD}
    ports:
      - 4018:4018
      - 4019:4019
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    links:
      - db
      - redis

volumes:
  chartbrew-db:
